/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCarne;
import Controlador.ControladorIngredienteAdicional;
import Controlador.ControladorPizzaBase;
import Controlador.ControladorSalsa;
import Controlador.ControladorVegetal;
import persistencia.CarneJpaController;
import Logica.Carne;
import java.awt.Container;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Julian
 */
public final class Interfaz extends javax.swing.JFrame {
    
    ControladorCarne controlCarne = new ControladorCarne ();
    ControladorPizzaBase controlPizzaBase = new ControladorPizzaBase ();
    ControladorVegetal controlVerdura = new ControladorVegetal ();
    ControladorSalsa controlSalsa = new ControladorSalsa ();
    ControladorIngredienteAdicional controlAdicional = new ControladorIngredienteAdicional ();
    
    /***********************************************************************************************************************/
    // Esgta sesion contiene los String [] que contiene toda la informacion a mostrar en el comboBox y la lista 
    String[] StringListaCarne;  
    String[] StringListaPizzaBase; 
    String[] StringListaVerduras; 
    String[] StringListaSalsas; 
    String[] StringListaAdicional; 
    String[] StringListaElementosEscogidos;
    /***********************************************************************************************************************/
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        this.StringListaCarne  = controlCarne.nombreCarnes ( );
        this.StringListaPizzaBase =  controlPizzaBase.nombrePizzabase();
        this.StringListaVerduras = controlVerdura.nombreVegetal();
        this.StringListaSalsas = controlSalsa.nombreSalsa();
        this.StringListaAdicional = controlAdicional.nombreIngredientes();
        this.StringListaElementosEscogidos = new String[4];
        for(int i=0;i<4;i++){StringListaElementosEscogidos[i]="";}
        
    /*this.StringListaCarne  = new String[] { "CARNE DE RES", "carne de pollo", "CARNE DE PATO", "CARNE DE CERDO ", "CARNE DE BUFALO ", " " };
    this.StringListaPizzaBase  = new String[] { "PIZZA BASE 1", "pizza base 2", "PIZZA BASE 3", "PIZZA BASE 4" };
    this.StringListaVerduras  = new String[] { "LECHUGA", "tomate", "ZANAHORIA", "PAPA", " " };
    this.StringListaSalsas  = new String[] { "SALSA DE TOMATE ", "salsa mayonesa", "SALSA ROSADA", "ALIOLI ", " " };
    this.StringListaAdicional  = new String[] { "INGREDIENTE ADICIONAL 1", "ingrediente adicional 2", "INGREDIENTE ADICIONAL 3", "INGREDIENTE ADICIONAL 4" };
    this.StringListaElementosEscogidos  = new String[] { "" };*/
        initComponents();
        initComboBox ();
        
    }
   
    
    
    public void initComboBox () { 
        jComboBoxPizza.setModel(new javax.swing.DefaultComboBoxModel(StringListaPizzaBase));
        jComboBoxCarne.setModel(new javax.swing.DefaultComboBoxModel(StringListaCarne));
        jComboBoxVerduras.setModel(new javax.swing.DefaultComboBoxModel(StringListaVerduras));
        jComboBoxSalsas.setModel(new javax.swing.DefaultComboBoxModel(StringListaSalsas));
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = StringListaElementosEscogidos;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        
        jComboBoxPizzaBaseCrud.setModel(new javax.swing.DefaultComboBoxModel(StringListaPizzaBase));
        jComboBoxCarneCrud.setModel(new javax.swing.DefaultComboBoxModel(StringListaCarne));
        jComboBoxVegetalesCrud.setModel(new javax.swing.DefaultComboBoxModel(StringListaVerduras));
        jComboBoxSalsaCrud.setModel(new javax.swing.DefaultComboBoxModel(StringListaSalsas));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanelAdministrador = new javax.swing.JPanel();
        jTabbedPaneCrudPizza = new javax.swing.JTabbedPane();
        jPanelCrudCarne = new javax.swing.JPanel();
        jPanelCarne = new javax.swing.JPanel();
        jComboBoxCarneCrud = new javax.swing.JComboBox();
        jButtonEliminarCarne = new javax.swing.JButton();
        jPanelCrearCarne = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTableCrearCarne = new javax.swing.JTable();
        jButtonCrearCarne = new javax.swing.JButton();
        jButtonActualizarCarne = new javax.swing.JButton();
        jPanelCrudVejetales = new javax.swing.JPanel();
        jPanelVegetales = new javax.swing.JPanel();
        jComboBoxVegetalesCrud = new javax.swing.JComboBox();
        jButtonEliminarVegetales = new javax.swing.JButton();
        jPanelCrearVegetales = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableCrearVegetales = new javax.swing.JTable();
        jButtonCrearVegetal = new javax.swing.JButton();
        jButtonActualizarVegetal = new javax.swing.JButton();
        jPanelCrudSalsas = new javax.swing.JPanel();
        jPanelSalsa = new javax.swing.JPanel();
        jComboBoxSalsaCrud = new javax.swing.JComboBox();
        jButtonEliminarSalsas = new javax.swing.JButton();
        jPanelCrearSalsas = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCrearSalsas = new javax.swing.JTable();
        jButtonCrearSalsa = new javax.swing.JButton();
        jButtonActualizarSalsa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelCrudIngredienteAdicional = new javax.swing.JPanel();
        jPanelCrudPizzaBase = new javax.swing.JPanel();
        jComboBoxPizzaBaseCrud = new javax.swing.JComboBox();
        jButtonEliminarPizzaBase = new javax.swing.JButton();
        jPanelCrearPizzaBase = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCrearPizzaBase = new javax.swing.JTable();
        jButtonCrearPizzaBase = new javax.swing.JButton();
        jButtonActualizarPizzaBase = new javax.swing.JButton();
        jPanelCliente = new javax.swing.JPanel();
        jComboBoxPizza = new javax.swing.JComboBox();
        jPanelIngredientesAdicionales = new javax.swing.JPanel();
        jComboBoxCarne = new javax.swing.JComboBox();
        jComboBoxVerduras = new javax.swing.JComboBox();
        jComboBoxSalsas = new javax.swing.JComboBox();
        jButtonEscogerCarne = new javax.swing.JButton();
        jButtonEscogerVerdura = new javax.swing.JButton();
        jButtonEscogerSalsa = new javax.swing.JButton();
        jButtonAnadirPizza = new javax.swing.JButton();
        jPanelEtemsEscogidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItemsEscgidos = new javax.swing.JList();
        jLabelFotoPizzaBase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonComprarGenerarFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jLabelFatura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPaneCrudPizza.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCarne.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxCarneCrud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonEliminarCarne.setText("ELIMININAR CARNE");
        jButtonEliminarCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCarneActionPerformed(evt);
            }
        });

        jPanelCrearCarne.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR"));

        jTableCrearCarne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_CARNE", "PRESENTACION", "CANTIDAD DE GRASAS", "PRECIO", "ANIMAL", "NOMBRE", "PRECIO/PORCION", "CANTIDAD", "TIPO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jTableCrearCarne);

        jButtonCrearCarne.setText("CREAR");
        jButtonCrearCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCarneActionPerformed(evt);
            }
        });

        jButtonActualizarCarne.setText("ACTUALIZAR");
        jButtonActualizarCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarCarneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearCarneLayout = new javax.swing.GroupLayout(jPanelCrearCarne);
        jPanelCrearCarne.setLayout(jPanelCrearCarneLayout);
        jPanelCrearCarneLayout.setHorizontalGroup(
            jPanelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCarneLayout.createSequentialGroup()
                .addGroup(jPanelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(jPanelCrearCarneLayout.createSequentialGroup()
                        .addComponent(jButtonCrearCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarCarne)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCrearCarneLayout.setVerticalGroup(
            jPanelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCarneLayout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanelCrearCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearCarne)
                    .addComponent(jButtonActualizarCarne)))
        );

        javax.swing.GroupLayout jPanelCarneLayout = new javax.swing.GroupLayout(jPanelCarne);
        jPanelCarne.setLayout(jPanelCarneLayout);
        jPanelCarneLayout.setHorizontalGroup(
            jPanelCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCarneLayout.createSequentialGroup()
                        .addComponent(jComboBoxCarneCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addComponent(jPanelCrearCarne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCarneLayout.setVerticalGroup(
            jPanelCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCarneCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarCarne))
                .addGap(18, 18, 18)
                .addComponent(jPanelCrearCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCrudCarneLayout = new javax.swing.GroupLayout(jPanelCrudCarne);
        jPanelCrudCarne.setLayout(jPanelCrudCarneLayout);
        jPanelCrudCarneLayout.setHorizontalGroup(
            jPanelCrudCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudCarneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCrudCarneLayout.setVerticalGroup(
            jPanelCrudCarneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudCarneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPaneCrudPizza.addTab("CARNE", jPanelCrudCarne);

        jPanelVegetales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxVegetalesCrud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonEliminarVegetales.setText("ELIMININAR VEGETAL");
        jButtonEliminarVegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarVegetalesActionPerformed(evt);
            }
        });

        jPanelCrearVegetales.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR Y ACTUALIZAR"));

        jTableCrearVegetales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_VEGETAL", "CARBONHIDRATOS", "PRECIO", "NOMBRE", "PRECIO PORCION", "CANTIDAD", "TIPO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTableCrearVegetales);

        jButtonCrearVegetal.setText("CREAR");
        jButtonCrearVegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearVegetalActionPerformed(evt);
            }
        });

        jButtonActualizarVegetal.setText("ACTUALIZAR");
        jButtonActualizarVegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarVegetalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearVegetalesLayout = new javax.swing.GroupLayout(jPanelCrearVegetales);
        jPanelCrearVegetales.setLayout(jPanelCrearVegetalesLayout);
        jPanelCrearVegetalesLayout.setHorizontalGroup(
            jPanelCrearVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearVegetalesLayout.createSequentialGroup()
                .addGroup(jPanelCrearVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(jPanelCrearVegetalesLayout.createSequentialGroup()
                        .addComponent(jButtonCrearVegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarVegetal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCrearVegetalesLayout.setVerticalGroup(
            jPanelCrearVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearVegetalesLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearVegetal)
                    .addComponent(jButtonActualizarVegetal))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelVegetalesLayout = new javax.swing.GroupLayout(jPanelVegetales);
        jPanelVegetales.setLayout(jPanelVegetalesLayout);
        jPanelVegetalesLayout.setHorizontalGroup(
            jPanelVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVegetalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVegetalesLayout.createSequentialGroup()
                        .addComponent(jComboBoxVegetalesCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addComponent(jPanelCrearVegetales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelVegetalesLayout.setVerticalGroup(
            jPanelVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVegetalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVegetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVegetalesCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarVegetales))
                .addGap(18, 18, 18)
                .addComponent(jPanelCrearVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCrudVejetalesLayout = new javax.swing.GroupLayout(jPanelCrudVejetales);
        jPanelCrudVejetales.setLayout(jPanelCrudVejetalesLayout);
        jPanelCrudVejetalesLayout.setHorizontalGroup(
            jPanelCrudVejetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(jPanelCrudVejetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudVejetalesLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelCrudVejetalesLayout.setVerticalGroup(
            jPanelCrudVejetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(jPanelCrudVejetalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudVejetalesLayout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(jPanelVegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        jTabbedPaneCrudPizza.addTab("VEGETALES", jPanelCrudVejetales);

        jPanelSalsa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxSalsaCrud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSalsaCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSalsaCrudActionPerformed(evt);
            }
        });

        jButtonEliminarSalsas.setText("ELIMININAR SALSAS");
        jButtonEliminarSalsas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarSalsasActionPerformed(evt);
            }
        });

        jPanelCrearSalsas.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR Y ACTUALIZAR"));

        jTableCrearSalsas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_SALSA", "AZUCARES", "CARBOHIDRATOS", "GRASA", "PRECIO", "NOMBRE", "PRECIO/PORCION", "CANTIDAD", "TIPO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableCrearSalsas);

        jButtonCrearSalsa.setText("CREAR");
        jButtonCrearSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSalsaActionPerformed(evt);
            }
        });

        jButtonActualizarSalsa.setText("ACTUALIZAR");
        jButtonActualizarSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarSalsaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearSalsasLayout = new javax.swing.GroupLayout(jPanelCrearSalsas);
        jPanelCrearSalsas.setLayout(jPanelCrearSalsasLayout);
        jPanelCrearSalsasLayout.setHorizontalGroup(
            jPanelCrearSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearSalsasLayout.createSequentialGroup()
                .addGroup(jPanelCrearSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(jPanelCrearSalsasLayout.createSequentialGroup()
                        .addComponent(jButtonCrearSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonActualizarSalsa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCrearSalsasLayout.setVerticalGroup(
            jPanelCrearSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearSalsasLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelCrearSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearSalsa)
                    .addComponent(jButtonActualizarSalsa))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSalsaLayout = new javax.swing.GroupLayout(jPanelSalsa);
        jPanelSalsa.setLayout(jPanelSalsaLayout);
        jPanelSalsaLayout.setHorizontalGroup(
            jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalsaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSalsaLayout.createSequentialGroup()
                        .addComponent(jComboBoxSalsaCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 241, Short.MAX_VALUE))
                    .addComponent(jPanelCrearSalsas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSalsaLayout.setVerticalGroup(
            jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalsaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSalsaCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarSalsas))
                .addGap(32, 32, 32)
                .addComponent(jPanelCrearSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCrudSalsasLayout = new javax.swing.GroupLayout(jPanelCrudSalsas);
        jPanelCrudSalsas.setLayout(jPanelCrudSalsasLayout);
        jPanelCrudSalsasLayout.setHorizontalGroup(
            jPanelCrudSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(jPanelCrudSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudSalsasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelCrudSalsasLayout.setVerticalGroup(
            jPanelCrudSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(jPanelCrudSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudSalsasLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jPanelSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );

        jTabbedPaneCrudPizza.addTab("SALSAS", jPanelCrudSalsas);

        jPanelCrudIngredienteAdicional.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCrudIngredienteAdicionalLayout = new javax.swing.GroupLayout(jPanelCrudIngredienteAdicional);
        jPanelCrudIngredienteAdicional.setLayout(jPanelCrudIngredienteAdicionalLayout);
        jPanelCrudIngredienteAdicionalLayout.setHorizontalGroup(
            jPanelCrudIngredienteAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jPanelCrudIngredienteAdicionalLayout.setVerticalGroup(
            jPanelCrudIngredienteAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelCrudIngredienteAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCrudIngredienteAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPaneCrudPizza.addTab("BORRAR", jPanel1);

        jPanelCrudPizzaBase.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxPizzaBaseCrud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPizzaBaseCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPizzaBaseCrudActionPerformed(evt);
            }
        });

        jButtonEliminarPizzaBase.setText("ELIMININAR PIZZA BASE");
        jButtonEliminarPizzaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPizzaBaseActionPerformed(evt);
            }
        });

        jPanelCrearPizzaBase.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR"));

        jTableCrearPizzaBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_PIZZA", "NOMBRE", "TAMAÑO", "PRESENTACION", "PRECIO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableCrearPizzaBase);

        jButtonCrearPizzaBase.setText("CREAR");
        jButtonCrearPizzaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPizzaBaseActionPerformed(evt);
            }
        });

        jButtonActualizarPizzaBase.setText("ACTUALIZAR");
        jButtonActualizarPizzaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarPizzaBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearPizzaBaseLayout = new javax.swing.GroupLayout(jPanelCrearPizzaBase);
        jPanelCrearPizzaBase.setLayout(jPanelCrearPizzaBaseLayout);
        jPanelCrearPizzaBaseLayout.setHorizontalGroup(
            jPanelCrearPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearPizzaBaseLayout.createSequentialGroup()
                .addGroup(jPanelCrearPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanelCrearPizzaBaseLayout.createSequentialGroup()
                        .addComponent(jButtonCrearPizzaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarPizzaBase)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCrearPizzaBaseLayout.setVerticalGroup(
            jPanelCrearPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearPizzaBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCrearPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearPizzaBase)
                    .addComponent(jButtonActualizarPizzaBase))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanelCrudPizzaBaseLayout = new javax.swing.GroupLayout(jPanelCrudPizzaBase);
        jPanelCrudPizzaBase.setLayout(jPanelCrudPizzaBaseLayout);
        jPanelCrudPizzaBaseLayout.setHorizontalGroup(
            jPanelCrudPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudPizzaBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrudPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrudPizzaBaseLayout.createSequentialGroup()
                        .addComponent(jComboBoxPizzaBaseCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarPizzaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 240, Short.MAX_VALUE))
                    .addComponent(jPanelCrearPizzaBase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCrudPizzaBaseLayout.setVerticalGroup(
            jPanelCrudPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrudPizzaBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrudPizzaBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPizzaBaseCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarPizzaBase))
                .addGap(32, 32, 32)
                .addComponent(jPanelCrearPizzaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPaneCrudPizza.addTab("PIZZA BASE", jPanelCrudPizzaBase);

        javax.swing.GroupLayout jPanelAdministradorLayout = new javax.swing.GroupLayout(jPanelAdministrador);
        jPanelAdministrador.setLayout(jPanelAdministradorLayout);
        jPanelAdministradorLayout.setHorizontalGroup(
            jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCrudPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 759, Short.MAX_VALUE)
        );
        jPanelAdministradorLayout.setVerticalGroup(
            jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCrudPizza, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane4.addTab("ADMINISTRADOR", jPanelAdministrador);

        jComboBoxPizza.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jComboBoxPizza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PIZZA BASE 1", "PIZZA BASE 2", "PIZZA BASE 3", "PIZZA BASE 4" }));
        jComboBoxPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPizzaActionPerformed(evt);
            }
        });

        jPanelIngredientesAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("INGREDIENTES ADICIONALES")));

        jComboBoxCarne.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jComboBoxCarne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CARNE DE RES", "CARNE DE POLLO", "CARNE DE PATO", "CARNE DE CERDO ", "CARNE DE BUFALO ", " " }));

        jComboBoxVerduras.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jComboBoxVerduras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LECHUGA", "TOMATE", "ZANAHORIA", "PAPA", " " }));

        jComboBoxSalsas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jComboBoxSalsas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SALSA DE TOMATE ", "SALSA MAYONESA", "SALSA ROSADA", "ALIOLI ", " " }));

        jButtonEscogerCarne.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButtonEscogerCarne.setText("ESCOGER CARNE ");
        jButtonEscogerCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogerCarneActionPerformed(evt);
            }
        });

        jButtonEscogerVerdura.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButtonEscogerVerdura.setText("ESCOGER VERDURA");
        jButtonEscogerVerdura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogerVerduraActionPerformed(evt);
            }
        });

        jButtonEscogerSalsa.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButtonEscogerSalsa.setText("ESCOGER SALSA");
        jButtonEscogerSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogerSalsaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIngredientesAdicionalesLayout = new javax.swing.GroupLayout(jPanelIngredientesAdicionales);
        jPanelIngredientesAdicionales.setLayout(jPanelIngredientesAdicionalesLayout);
        jPanelIngredientesAdicionalesLayout.setHorizontalGroup(
            jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientesAdicionalesLayout.createSequentialGroup()
                .addGroup(jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxSalsas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxVerduras, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCarne, javax.swing.GroupLayout.Alignment.LEADING, 0, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonEscogerVerdura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jButtonEscogerCarne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEscogerSalsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelIngredientesAdicionalesLayout.setVerticalGroup(
            jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngredientesAdicionalesLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEscogerCarne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVerduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEscogerVerdura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIngredientesAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEscogerSalsa))
                .addGap(28, 28, 28))
        );

        jButtonAnadirPizza.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButtonAnadirPizza.setText("AÑADIR PIZZA BASE");
        jButtonAnadirPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirPizzaActionPerformed(evt);
            }
        });

        jPanelEtemsEscogidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Items Escogidos"));

        jListItemsEscgidos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "PIZZA BASE 1", "INGREDIENTE ADICIONAL 1", "CARNE DE RES", "...", "..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItemsEscgidos);

        jLabelFotoPizzaBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/pizza.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("FOTO PIZZA BASE: ");

        javax.swing.GroupLayout jPanelEtemsEscogidosLayout = new javax.swing.GroupLayout(jPanelEtemsEscogidos);
        jPanelEtemsEscogidos.setLayout(jPanelEtemsEscogidosLayout);
        jPanelEtemsEscogidosLayout.setHorizontalGroup(
            jPanelEtemsEscogidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEtemsEscogidosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEtemsEscogidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFotoPizzaBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanelEtemsEscogidosLayout.setVerticalGroup(
            jPanelEtemsEscogidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEtemsEscogidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEtemsEscogidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addGroup(jPanelEtemsEscogidosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFotoPizzaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonComprarGenerarFactura.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButtonComprarGenerarFactura.setText("COMPRAR Y GENERAR FACTURA ");
        jButtonComprarGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarGenerarFacturaActionPerformed(evt);
            }
        });

        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FECHA", "INFO", "COSTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFactura);
        if (jTableFactura.getColumnModel().getColumnCount() > 0) {
            jTableFactura.getColumnModel().getColumn(0).setResizable(false);
            jTableFactura.getColumnModel().getColumn(1).setResizable(false);
            jTableFactura.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabelFatura.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabelFatura.setText("FACTURA");

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabelFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonComprarGenerarFactura))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jComboBoxPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAnadirPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelIngredientesAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jPanelEtemsEscogidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelEtemsEscogidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnadirPizza))
                        .addGap(29, 29, 29)
                        .addComponent(jPanelIngredientesAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonComprarGenerarFactura)
                    .addComponent(jLabelFatura))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("CLIENTE ", jPanelCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprarGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarGenerarFacturaActionPerformed
        // TODO add your handling code here:
        System.out.println ("generar factura  ");
        
        
        Container contenedor = new Container();
         
        
    }//GEN-LAST:event_jButtonComprarGenerarFacturaActionPerformed

    private void jButtonEscogerCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogerCarneActionPerformed
        // TODO add your handling code here:
        String ingrediente = jComboBoxCarne.getSelectedItem().toString();

        StringListaElementosEscogidos[1] = ingrediente;
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = StringListaElementosEscogidos;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButtonEscogerCarneActionPerformed

    private void jButtonEscogerVerduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogerVerduraActionPerformed
        // TODO add your handling code here:
        String ingrediente = jComboBoxVerduras.getSelectedItem().toString();
        
        StringListaElementosEscogidos[2]  = ingrediente;
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = StringListaElementosEscogidos;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButtonEscogerVerduraActionPerformed

    private void jButtonEscogerSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogerSalsaActionPerformed
        // TODO add your handling code here:
 
        String ingrediente = jComboBoxSalsas.getSelectedItem().toString();

        StringListaElementosEscogidos[3]  = ingrediente;
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = StringListaElementosEscogidos;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButtonEscogerSalsaActionPerformed

    private void jButtonAnadirPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirPizzaActionPerformed
        // TODO add your handling code here:
        String ingrediente = jComboBoxPizza.getSelectedItem().toString();
        StringListaElementosEscogidos[0]  = ingrediente;
        jListItemsEscgidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = StringListaElementosEscogidos;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButtonAnadirPizzaActionPerformed

    private void jComboBoxPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPizzaActionPerformed

    private void jButtonActualizarPizzaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarPizzaBaseActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearPizzaBase.getModel().getValueAt(0, 0).toString();
        String nomb = jTableCrearPizzaBase.getModel().getValueAt(0, 1).toString();
        int tam = Integer.parseInt(jTableCrearPizzaBase.getModel().getValueAt(0, 2).toString());
        String present = jTableCrearPizzaBase.getModel().getValueAt(0, 3).toString();
        float price = Float.parseFloat(jTableCrearPizzaBase.getModel().getValueAt(0, 4).toString());
        String foto = jTableCrearPizzaBase.getModel().getValueAt(0, 5).toString();
        try {
            controlPizzaBase.actualizarPizza(id, nomb, tam, present, price, new byte[1]);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonActualizarPizzaBaseActionPerformed

    private void jButtonCrearPizzaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPizzaBaseActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearPizzaBase.getModel().getValueAt(0, 0).toString();
        String nomb = jTableCrearPizzaBase.getModel().getValueAt(0, 1).toString();
        int tam = Integer.parseInt(jTableCrearPizzaBase.getModel().getValueAt(0, 2).toString());
        String present = jTableCrearPizzaBase.getModel().getValueAt(0, 3).toString();
        float price = Float.parseFloat(jTableCrearPizzaBase.getModel().getValueAt(0, 4).toString());
        String foto = jTableCrearPizzaBase.getModel().getValueAt(0, 5).toString();
        try {
            controlPizzaBase.agregarPizzaBase(id, nomb, tam, present, price, new byte[1]);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearPizzaBaseActionPerformed

    private void jButtonEliminarPizzaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPizzaBaseActionPerformed
        // TODO add your handling code here:
        try {
            controlPizzaBase.eliminarPizza(jComboBoxPizzaBaseCrud);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarPizzaBaseActionPerformed

    private void jComboBoxPizzaBaseCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPizzaBaseCrudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPizzaBaseCrudActionPerformed

    private void jButtonActualizarSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarSalsaActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearSalsas.getModel().getValueAt(0, 0).toString();
        String azucar = jTableCrearSalsas.getModel().getValueAt(0, 1).toString();
        int carbo = Integer.parseInt(jTableCrearSalsas.getModel().getValueAt(0, 2).toString());
        float grasa = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 3).toString());
        float precio = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 4).toString());
        String nombre = jTableCrearSalsas.getModel().getValueAt(0, 5).toString();
        float pp = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 6).toString());
        int cantidad = Integer.parseInt(jTableCrearSalsas.getModel().getValueAt(0, 7).toString());
        String tipo = jTableCrearSalsas.getModel().getValueAt(0, 8).toString();
        String foto = jTableCrearSalsas.getModel().getValueAt(0, 9).toString();

        try {
            controlSalsa.actualizarSalsa(id, "S"+id, nombre, pp, cantidad, tipo, new byte[2], azucar, carbo, grasa);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonActualizarSalsaActionPerformed

    private void jButtonCrearSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSalsaActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearSalsas.getModel().getValueAt(0, 0).toString();
        String azucar = jTableCrearSalsas.getModel().getValueAt(0, 1).toString();
        int carbo = Integer.parseInt(jTableCrearSalsas.getModel().getValueAt(0, 2).toString());
        float grasa = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 3).toString());
        float precio = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 4).toString());
        String nombre = jTableCrearSalsas.getModel().getValueAt(0, 5).toString();
        float pp = Float.parseFloat(jTableCrearSalsas.getModel().getValueAt(0, 6).toString());
        int cantidad = Integer.parseInt(jTableCrearSalsas.getModel().getValueAt(0, 7).toString());
        String tipo = jTableCrearSalsas.getModel().getValueAt(0, 8).toString();
        String foto = jTableCrearSalsas.getModel().getValueAt(0, 9).toString();

        try {
            controlSalsa.agregarSalsa(id, "S"+id, nombre, pp, cantidad, tipo, new byte[2], azucar, carbo, grasa);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearSalsaActionPerformed

    private void jButtonEliminarSalsasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarSalsasActionPerformed
        // TODO add your handling code here:
        try {
            controlSalsa.eliminarSalsa(jComboBoxSalsaCrud);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*controlCarne *
        controlPizzaBase *
        controlVerdura *
        controlSalsa *
        controlAdicional * */
    }//GEN-LAST:event_jButtonEliminarSalsasActionPerformed

    private void jComboBoxSalsaCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSalsaCrudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSalsaCrudActionPerformed

    private void jButtonActualizarVegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarVegetalActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearVegetales.getModel().getValueAt(0, 0).toString();
        int carbo = Integer.parseInt(jTableCrearVegetales.getModel().getValueAt(0, 1).toString());
        float precio = Float.parseFloat(jTableCrearVegetales.getModel().getValueAt(0, 2).toString());
        String nombre = jTableCrearVegetales.getModel().getValueAt(0, 3).toString();
        float pp = Float.parseFloat(jTableCrearVegetales.getModel().getValueAt(0, 4).toString());
        int cantidad = Integer.parseInt(jTableCrearVegetales.getModel().getValueAt(0, 5).toString());
        String tipo = jTableCrearVegetales.getModel().getValueAt(0, 6).toString();
        String foto = jTableCrearVegetales.getModel().getValueAt(0, 7).toString();

        try {
            controlVerdura.actualizarVegetal(id, "V"+id, nombre, pp, cantidad, tipo, new byte[1], carbo);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonActualizarVegetalActionPerformed

    private void jButtonCrearVegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearVegetalActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearVegetales.getModel().getValueAt(0, 0).toString();
        int carbo = Integer.parseInt(jTableCrearVegetales.getModel().getValueAt(0, 1).toString());
        float precio = Float.parseFloat(jTableCrearVegetales.getModel().getValueAt(0, 2).toString());
        String nombre = jTableCrearVegetales.getModel().getValueAt(0, 3).toString();
        float pp = Float.parseFloat(jTableCrearVegetales.getModel().getValueAt(0, 4).toString());
        int cantidad = Integer.parseInt(jTableCrearVegetales.getModel().getValueAt(0, 5).toString());
        String tipo = jTableCrearVegetales.getModel().getValueAt(0, 6).toString();
        String foto = jTableCrearVegetales.getModel().getValueAt(0, 7).toString();

        try {
            controlVerdura.agregarVegetal(id, "V"+id, nombre, pp, cantidad, tipo, new byte[1], carbo);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearVegetalActionPerformed

    private void jButtonEliminarVegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarVegetalesActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            controlVerdura.eliminarVegetal(jComboBoxVegetalesCrud);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarVegetalesActionPerformed

    private void jButtonActualizarCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarCarneActionPerformed
        String id = jTableCrearCarne.getModel().getValueAt(0, 0).toString();
        String pres = jTableCrearCarne.getModel().getValueAt(0, 1).toString();
        float grasa = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 2).toString());
        float price = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 3).toString());
        String animal = jTableCrearCarne.getModel().getValueAt(0, 4).toString();
        String nombre = jTableCrearCarne.getModel().getValueAt(0, 5).toString();
        float pp = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 6).toString());
        int cantidad = Integer.parseInt(jTableCrearCarne.getModel().getValueAt(0, 7).toString());
        String tipo = jTableCrearCarne.getModel().getValueAt(0, 8).toString();
        String foto = jTableCrearCarne.getModel().getValueAt(0, 9).toString();

        try {
            controlCarne.actualizarCarne(id, "C"+id, nombre, pp, cantidad, tipo, new byte[1], pres, grasa, animal);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonActualizarCarneActionPerformed

    private void jButtonCrearCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCarneActionPerformed
        // TODO add your handling code here:
        String id = jTableCrearCarne.getModel().getValueAt(0, 0).toString();
        String pres = jTableCrearCarne.getModel().getValueAt(0, 1).toString();
        float grasa = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 2).toString());
        float price = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 3).toString());
        String animal = jTableCrearCarne.getModel().getValueAt(0, 4).toString();
        String nombre = jTableCrearCarne.getModel().getValueAt(0, 5).toString();
        float pp = Float.parseFloat(jTableCrearCarne.getModel().getValueAt(0, 6).toString());
        int cantidad = Integer.parseInt(jTableCrearCarne.getModel().getValueAt(0, 7).toString());
        String tipo = jTableCrearCarne.getModel().getValueAt(0, 8).toString();
        String foto = jTableCrearCarne.getModel().getValueAt(0, 9).toString();

        try {
            controlCarne.agregarCarne(id, "C"+id, nombre, pp, cantidad, tipo, new byte[1], pres, grasa, animal);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearCarneActionPerformed

    private void jButtonEliminarCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCarneActionPerformed
        try {
            // TODO add your handling code here:
            controlCarne.eliminarCarne(jComboBoxCarneCrud);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarCarneActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarCarne;
    private javax.swing.JButton jButtonActualizarPizzaBase;
    private javax.swing.JButton jButtonActualizarSalsa;
    private javax.swing.JButton jButtonActualizarVegetal;
    private javax.swing.JButton jButtonAnadirPizza;
    private javax.swing.JButton jButtonComprarGenerarFactura;
    private javax.swing.JButton jButtonCrearCarne;
    private javax.swing.JButton jButtonCrearPizzaBase;
    private javax.swing.JButton jButtonCrearSalsa;
    private javax.swing.JButton jButtonCrearVegetal;
    private javax.swing.JButton jButtonEliminarCarne;
    private javax.swing.JButton jButtonEliminarPizzaBase;
    private javax.swing.JButton jButtonEliminarSalsas;
    private javax.swing.JButton jButtonEliminarVegetales;
    private javax.swing.JButton jButtonEscogerCarne;
    private javax.swing.JButton jButtonEscogerSalsa;
    private javax.swing.JButton jButtonEscogerVerdura;
    private javax.swing.JComboBox jComboBoxCarne;
    private javax.swing.JComboBox jComboBoxCarneCrud;
    private javax.swing.JComboBox jComboBoxPizza;
    private javax.swing.JComboBox jComboBoxPizzaBaseCrud;
    private javax.swing.JComboBox jComboBoxSalsaCrud;
    private javax.swing.JComboBox jComboBoxSalsas;
    private javax.swing.JComboBox jComboBoxVegetalesCrud;
    private javax.swing.JComboBox jComboBoxVerduras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFatura;
    private javax.swing.JLabel jLabelFotoPizzaBase;
    private javax.swing.JList jListItemsEscgidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdministrador;
    private javax.swing.JPanel jPanelCarne;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelCrearCarne;
    private javax.swing.JPanel jPanelCrearPizzaBase;
    private javax.swing.JPanel jPanelCrearSalsas;
    private javax.swing.JPanel jPanelCrearVegetales;
    private javax.swing.JPanel jPanelCrudCarne;
    private javax.swing.JPanel jPanelCrudIngredienteAdicional;
    private javax.swing.JPanel jPanelCrudPizzaBase;
    private javax.swing.JPanel jPanelCrudSalsas;
    private javax.swing.JPanel jPanelCrudVejetales;
    private javax.swing.JPanel jPanelEtemsEscogidos;
    private javax.swing.JPanel jPanelIngredientesAdicionales;
    private javax.swing.JPanel jPanelSalsa;
    private javax.swing.JPanel jPanelVegetales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPaneCrudPizza;
    private javax.swing.JTable jTableCrearCarne;
    private javax.swing.JTable jTableCrearPizzaBase;
    private javax.swing.JTable jTableCrearSalsas;
    private javax.swing.JTable jTableCrearVegetales;
    private javax.swing.JTable jTableFactura;
    // End of variables declaration//GEN-END:variables
}
